server:
  port: 8081
google:
  auth-uri: "https://accounts.google.com/o/oauth2/auth"
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

github:
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}
  redirect-uri: http://localhost:8081/oauth2/authorization/github/callback
  auth-uri: https://github.com/login/oauth/authorize?client_id=${github.client-id}&response_type=code&redirect_url=${github.redirect-uri}
  access-uri: https://github.com/login/oauth/access_token

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
okta:
  oauth2:
    client:
      client-id: ${OKTA_CLIENT_ID}
      client-secret: ${OKTA_CLIENT_SECRET}
      authorization-uri: https://dev-14986880.okta.com/oauth2/default/v1/authorize
logging:
  level:
    com.example.oidcoauth2spring.client.GithubClientAuthorization: DEBUG
