server:
  port: 8081

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: http://localhost:8081/oauth2/authorization/google/callback
  auth-uri: https://accounts.google.com/o/oauth2/v2/auth?client_id=${google.client-id}&scope=profile+email&redirect_uri=${google.redirect-uri}&response_type=code&redirect_url=${google.redirect-uri}
  access-uri: https://www.googleapis.com/oauth2/v4/token
  user-info: https://www.googleapis.com/oauth2/v3/userinfo

github:
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}
  redirect-uri: http://localhost:8081/oauth2/authorization/github/callback
  auth-uri: https://github.com/login/oauth/authorize?client_id=${github.client-id}&response_type=code&redirect_url=${github.redirect-uri}
  access-uri: https://github.com/login/oauth/access_token

facebook:
  client-id: ${FACEBOOK_CLIENT_ID}
  client-secret: ${FACEBOOK_CLIENT_SECRET}
  redirect-uri: http://localhost:8081/oauth2/authorization/facebook/callback
  auth-uri: https://www.facebook.com/v16.0/dialog/oauth?client_id=${facebook.client-id}&redirect_uri=${facebook.redirect-uri}&state=sadfsd
  access-uri: https://graph.facebook.com/v16.0/oauth/access_token?client_id=${facebook.client-id}&client_secret=${facebook.client-secret}&code={code-parameter}

okta:
  oauth2:
    client:
      client-id: ${OKTA_CLIENT_ID}
      client-secret: ${OKTA_CLIENT_SECRET}
      authorization-uri: https://dev-14986880.okta.com/oauth2/default/v1/authorize
